library(tidyverse)


# NB A REFAIRE (COMME TOUT LE RESTE) UNE FOIS QUE LES COQUILLES DE FORME DE VIE SERONT CORRIGEES AVEC LE DATA PAPER


# Load data ####

# trait data
MEAN <- read.csv2("outputs/data/mean_attribute_per_treatment_subset_nat_sab_int_SM_H_13C.csv")
MEAN_site <- read.csv2("outputs/data/mean_attribute_per_treatment_subset_nat_sab_int_site_level.csv")
traits <- c("LDMC","SLA","L_Area",
            "LCC","LNC","Ldelta13C",#"LPC",
            "Hrepro"   , #"Dmax"  , #    "Dmin" ,"Hveg"  , "H_FLORE",#
            "Disp", #"Mat_Per", #"Mat","Flo","FLO_FLORE", #
            "SeedMass"
)

# abundance data
ab_fer <- read.csv2("outputs/data/abundance_fertile.csv") %>% 
  rename(transect = id_transect_quadrat)
ab_nat <- read.csv2("outputs/data/abundance_natif.csv") %>% 
  filter(depth == "S") %>% 
  select(-depth) %>% 
  rename(transect = Ligne)

# Join abundance datasets
ab_fer2 <- ab_fer %>% 
  select(any_of(colnames(ab_nat))) %>% 
  mutate(treatment = "Fer")
ab_nat2 <- ab_nat %>% 
  mutate(treatment = "Nat") %>% 
  select(all_of(colnames(ab_fer2)))
ab <- rbind(ab_fer2,ab_nat2) %>% 
  mutate(LifeHistory = if_else(LifeForm1 == "The","annual","perennial")) %>% 
  select(species,code_sp,LifeForm1,LifeHistory,treatment,paddock,transect,abundance)


# Functions ####

compute_cwm <- function(ab,MEAN,MEAN_site, traits,level_of_trait_averaging){
  # This function computes CWM on all the traits.
  # ab: abundance data
  # MEAN: mean trait values at the treatment level
  # MEAN_site: mean trait values at the site level
  # traits: vector of names of traits
  # level_of-trait_averaging: either "treatment" or "site"
  
  if (level_of_trait_averaging == "treatment"){
    fMEAN <- MEAN %>% 
      select("species","code_sp","LifeForm1","LifeHistory","treatment",
             all_of(traits))
  } else if (level_of_trait_averaging == "site") {
    fMEAN <- MEAN_site %>% 
      select("species","code_sp","LifeForm1","LifeHistory",
             all_of(traits))
  }
  
  ab_traits <- ab %>% 
    left_join(fMEAN) %>% 
    group_by(transect,LifeHistory,treatment) %>% 
    mutate(relat_ab = abundance/sum(abundance)) 
    
  data_cwm <- ab_traits %>% 
    mutate_at(vars(all_of(traits)),
              .funs = list(CWM = ~ weighted.mean(.,relat_ab,na.rm=T) )) %>% 
    rename_at( vars( contains( "_CWM") ), list( ~paste("CWM", gsub("_CWM", "", .), sep = "_") ) ) %>% 
    unique() %>% 
    select(LifeHistory,treatment,paddock, transect,starts_with("CWM")) %>% 
    unique() %>% 
    rename_at( vars( contains( "CWM_") ), list( ~ gsub("CWM_", "", .) ) )
  
  data_cwm
}


get_cwm_decomposition <- function(ftrait,CWM,CWMfixed){
  # From the data frames of CWM and CWM fixed, generated by compute_cwm, this function returns a data frame 
  # with a row = a life history in a given transect
  # and with info on CWM, CWM fixed, and CWM intra (cf. Siefert 2015, box 1)
  # all computed for the desired trait
  
  # make a data frame with variation at these levels
  fCWM <- CWM %>% 
    select(LifeHistory,treatment,paddock,transect, all_of(ftrait)) %>% 
    mutate(CWM = get(ftrait)) %>% 
    select(-ftrait)
  fCWMfixed <- CWMfixed %>% 
    select(LifeHistory,treatment,paddock,transect, all_of(ftrait)) %>% 
    mutate(CWMfixed = get(ftrait)) %>% 
    select(-ftrait)
  
  # CWM data for the focal trait, at the three levels
  fCWMall <- full_join(fCWM,fCWMfixed) %>% 
    mutate(CWMintra = CWM - CWMfixed)
  fCWMall
}


compute_SS <- function(data,LH){ 
  # data is a data frame with a row = a life history in a given transect
  # and with info on CWM, CWM fixed, and CWM intra (cf. Siefert 2015, box 1)
  # it is the output of get_cwm_decomposition
  data_LH <- data %>% 
    filter(LifeHistory == LH)
  
  modtot <- lm(CWM ~ 1, data = data_LH)
  anotot <- anova(modtot)
  SStot <- anotot$`Sum Sq`
  
  modfixed <- lm(CWMfixed ~ 1, data = data_LH)
  anofixed <- anova(modfixed)
  SSfixed <- anofixed$`Sum Sq`
  
  modintra <- lm(CWMintra ~ 1, data = data_LH)
  anointra <- anova(modintra)
  SSintra <- anointra$`Sum Sq`
  
  SScov <- 100*(SStot - SSintra - SSfixed)/SStot
  
  data.frame(SStot = SStot,SSfixed = SSfixed,SSintra = SSintra ,SScov = SScov)
}

compute_aITV <- function(SumSq){
  aITV <- log(SumSq$SSintra/SumSq$SSfixed)
  aITV
}

# Analyses ####

# CWM with both species replacement and intrasp variability  
CWM <- compute_cwm(ab,MEAN,MEAN_site,traits,level_of_trait_averaging = "treatment")
# CWM with species replacement but no intraspecific variability
CWMfixed <- compute_cwm(ab,MEAN,MEAN_site,traits,level_of_trait_averaging = "site")
# CWM intra  = CWM - CWMfixed pour chaque trait

ftrait <- "SLA"
fCWMall <- get_cwm_decomposition(ftrait,CWM,CWMfixed)

fCWMall %>% 
  ggplot(aes(x=CWMfixed,y=CWM,color=treatment)) +
  geom_point()

fLH <- "annual"
SumSq <- compute_SS(fCWMall,fLH) %>% 
  mutate(sum = SSfixed + SSintra + SScov) # vérifier que SStot = SSfixed + SSintra + SScov. Pas le cas, visiblement...


SumSq %>% 
  gather(key = level,value = sq) %>% 
  ggplot(aes(x=level,y=sq))+
  geom_point()



AITV <- NULL
TRAIT <- NULL
LH <- NULL
for (ftrait in traits){
  # compute the 3 CWM on this trait, for each LH in each transect
  fCWMall <- get_cwm_decomposition(ftrait,CWM,CWMfixed) 
  for (fLH in c("annual","perennial")){
    # compute aITV for each LH
    aITV <- compute_SS(fCWMall,fLH) %>% compute_aITV()
    AITV <- c(AITV,aITV)
    TRAIT <- c(TRAIT,ftrait)
    LH <- c(LH,fLH)
  }
}

data_aITV <- data.frame(aITV = AITV, trait = TRAIT,LifeHistory = LH) %>% 
  spread(key = LifeHistory,value=aITV) %>% 
  arrange(factor(trait),levels = traits) %>% 
  filter(!(trait %in% c("Hrepro","SeedMass","Ldelta13C")))
# If aITV inferior to zero: greater contribution of species turnover to total among-community variance

data_aITV %>% 
  filter(!(trait %in% c("Hrepro","SeedMass","Ldelta13C"))) %>% 
  ggplot(aes(x=perennial,y=annual,label = trait))+
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  xlim(c(0-10,2)) +
  ylim(c(-4,2)) +
  geom_label()
