library(tidyverse)


# NB A REFAIRE (COMME TOUT LE RESTE) UNE FOIS QUE LES COQUILLES DE FORME DE VIE SERONT CORRIGEES AVEC LE DATA PAPER


# Load data ####

# trait data
MEAN <- read.csv2("outputs/data/mean_attribute_per_treatment_subset_nat_sab_int_SM.csv")
MEAN_site <- read.csv2("outputs/data/mean_attribute_per_treatment_subset_nat_sab_int_site_level.csv")
traits <- c("LDMC","SLA","L_Area",
            "LCC","LNC","Ldelta13C",#"LPC",
            "Hrepro"   , #"Dmax"  , #    "Dmin" ,"Hveg"  , "H_FLORE",#
            "Disp", #"Mat_Per", #"Mat","Flo","FLO_FLORE", #
            "SeedMass"
)

# abundance data
ab_fer <- read.csv2("outputs/data/abundance_fertile.csv") %>% 
  rename(transect = id_transect_quadrat)
ab_nat <- read.csv2("outputs/data/abundance_natif.csv") %>% 
  filter(depth == "S") %>% 
  select(-depth) %>% 
  rename(transect = Ligne)

# Join abundance datasets
ab_fer2 <- ab_fer %>% 
  select(any_of(colnames(ab_nat))) %>% 
  mutate(treatment = "Fer")
ab_nat2 <- ab_nat %>% 
  mutate(treatment = "Nat") %>% 
  select(all_of(colnames(ab_fer2)))
ab <- rbind(ab_fer2,ab_nat2) %>% 
  mutate(LifeHistory = if_else(LifeForm1 == "The","annual","perennial")) %>% 
  select(species,code_sp,LifeForm1,LifeHistory,treatment,paddock,transect,abundance)


# Functions ####

compute_cwm <- function(ab,MEAN,MEAN_site, traits,level_of_trait_averaging){
  # This function computes CWM on all the traits.
  # ab: abundance data
  # MEAN: mean trait values at the treatment level
  # MEAN_site: mean trait values at the site level
  # traits: vector of names of traits
  # level_of-trait_averaging: either "treatment" or "site"
  
  if (level_of_trait_averaging == "treatment"){
    fMEAN <- MEAN %>% 
      select("species","code_sp","LifeForm1","LifeHistory","treatment",
             all_of(traits))
  } else if (level_of_trait_averaging == "site") {
    fMEAN <- MEAN_site %>% 
      select("species","code_sp","LifeForm1","LifeHistory",
             all_of(traits))
  }
  
  ab_traits <- ab %>% 
    left_join(fMEAN) %>% 
    group_by(transect,LifeHistory,treatment) %>% 
    mutate(relat_ab = abundance/sum(abundance)) 
    
  data_cwm <- ab_traits %>% 
    mutate_at(vars(all_of(traits)),
              .funs = list(CWM = ~ weighted.mean(.,relat_ab,na.rm=T) )) %>% 
    rename_at( vars( contains( "_CWM") ), list( ~paste("CWM", gsub("_CWM", "", .), sep = "_") ) ) %>% 
    unique() %>% 
    select(LifeHistory,treatment,paddock, transect,starts_with("CWM")) %>% 
    unique() %>% 
    rename_at( vars( contains( "CWM_") ), list( ~ gsub("CWM_", "", .) ) )
  
  data_cwm
}


get_cwm_decomposition <- function(ftrait,CWM,CWMfixed){
  # From the data frames of CWM and CWM fixed, generated by compute_cwm, this function returns a data frame 
  # with a row = a life history in a given transect
  # and with info on CWM, CWM fixed, and CWM intra (cf. Siefert 2015, box 1)
  # all computed for the desired trait
  
  # make a data frame with variation at these levels
  fCWM <- CWM %>% 
    select(LifeHistory,treatment,paddock,transect, all_of(ftrait)) %>% 
    mutate(CWM = get(ftrait)) %>% 
    select(-ftrait)
  fCWMfixed <- CWMfixed %>% 
    select(LifeHistory,treatment,paddock,transect, all_of(ftrait)) %>% 
    mutate(CWMfixed = get(ftrait)) %>% 
    select(-ftrait)
  
  # CWM data for the focal trait, at the three levels
  fCWMall <- full_join(fCWM,fCWMfixed) %>% 
    mutate(CWMintra = CWM - CWMfixed)
  fCWMall
}


compute_SS <- function(data,LH){ 
  # data is a data frame with a row = a life history in a given transect
  # and with info on CWM, CWM fixed, and CWM intra (cf. Siefert 2015, box 1)
  # it is the output of get_cwm_decomposition
  data_LH <- data %>% 
    filter(LifeHistory == LH)
  
  modtot <- lm(CWM ~ 1, data = data_LH)
  anotot <- anova(modtot)
  SStot <- anotot$`Sum Sq`
  
  modfixed <- lm(CWMfixed ~ 1, data = data_LH)
  anofixed <- anova(modfixed)
  SSfixed <- anofixed$`Sum Sq`
  
  modintra <- lm(CWMintra ~ 1, data = data_LH)
  anointra <- anova(modintra)
  SSintra <- anointra$`Sum Sq`
  
  SScov <- 100*(SStot - SSintra - SSfixed)/SStot # BIZARRE, CETTE FORMULE NE DONNE PAS somme(SS) = SStot...
  
  data.frame(SStot = SStot,SSfixed = SSfixed,SSintra = SSintra ,SScov = SScov)
}



# Analyses ####

# CWM with both species replacement and intrasp variability  
CWM <- compute_cwm(ab,MEAN,MEAN_site,traits,level_of_trait_averaging = "treatment")
# CWM with species replacement but no intraspecific variability
CWMfixed <- compute_cwm(ab,MEAN,MEAN_site,traits,level_of_trait_averaging = "site")
# CWM intra  = CWM - CWMfixed pour chaque trait


## CWM change f(LH) ####


traits_names <- c("Leaf Dry Matter Content (mg/g)", "Specific Leaf Area (mm²/mg)"," Leaf Area (cm²) (log scale)",
                  "Leaf Carbon Content (mg/g)","Leaf Nitrogen Content (mg/g)", "Leaf delta 13C (part per thousand)",
                  "Reproductive Height (cm)", 
                  "Date of first dispersal (Julian day)",
                  "Seed Mass (mg)")

i <- 0
PLOTS <- NULL
for (ftrait in traits){
  i <- i+1
  plot <- CWM %>%
    mutate(LifeHistory = if_else(LifeHistory == "annual","Annuals","Perennials")) %>% 
    # mutate(Management = factor(Management, levels = c("Intensive","Extensive"))) %>% 
    mutate(treatment = factor(treatment,levels = c("Fer","Nat"))) %>% 
    ggplot(aes_string(x = "treatment",y= ftrait,fill = "treatment")) +
    facet_wrap(~LifeHistory,strip.position = "bottom") +
    geom_boxplot() +
    geom_point() +
    theme_classic() +
    scale_fill_manual(values = c("grey", "white")) +
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank() ,
          axis.title.x = element_blank(),
          axis.title.y = element_blank()
    ) +
    theme(legend.position="none") +
    theme(legend.title.align = 50) +
    ggtitle(traits_names[i]) +
    {if(ftrait == "L_Area")scale_y_continuous(trans='log10')}
  PLOTS[[i]] <- plot
}

  
plot <- CWM %>%
  rename(Management = treatment) %>% 
  mutate(LifeHistory = if_else(LifeHistory == "annual","Annuals","Perennials")) %>% 
  mutate(Management = if_else(Management == "Fer","Intensive","Extensive")) %>% 
  ggplot(aes_string(x = "Management",y= ftrait,fill = "Management")) +
  facet_wrap(~LifeHistory,strip.position = "bottom") +
  geom_boxplot() +
  # geom_point() +
  theme_classic() +
  scale_fill_manual(values = c("grey", "white")) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank() ,
        axis.title.x = element_blank(),
        axis.title.y = element_blank()
  ) +
  theme(legend.title.align = 50) +
  ggtitle(traits_names[i])
leg <- ggpubr::get_legend(plot)
legend <- ggpubr::as_ggplot(leg)

boxplot_all_traits <- ggpubr::ggarrange(PLOTS[[1]],PLOTS[[2]],PLOTS[[3]],PLOTS[[4]],PLOTS[[5]],PLOTS[[6]],
                                        PLOTS[[7]],PLOTS[[8]],PLOTS[[9]],legend,
                                        ncol = 3,nrow = 4)

ggsave("draft/boxplot_CWM_all_traits.jpg",boxplot_all_traits,width = 10, height = 10)


fCWMall <- get_cwm_decomposition(ftrait,CWM,CWMfixed)
fCWMall %>% 
  ggplot(aes(x=CWMfixed,y=CWM,color=treatment)) +
  geom_point()

fLH <- "annual"
SumSq <- compute_SS(fCWMall,fLH) %>% 
  mutate(sum = SSfixed + SSintra + SScov) # vérifier que SStot = SSfixed + SSintra + SScov. Pas le cas, visiblement...
# A VERIFIER!
# (après, je ne m'intéresse aps à la covariance... Si, peut-être ?)
# Je peux produire le graphe de la contribution relative de chaque variance pour annuelles et pérennes
# En disant bien que la variance est plus forte chez les pérennes




AITV <- NULL
TRAIT <- NULL
LH <- NULL
SUMSQ <- NULL
for (ftrait in traits){
  # compute the 3 CWM on this trait, for each LH in each transect
  fCWMall <- get_cwm_decomposition(ftrait,CWM,CWMfixed) 
  for (fLH in c("annual","perennial")){
    SumSq <- compute_SS(fCWMall,fLH) %>% 
      mutate(trait = ftrait,LifeHistory = fLH)
    # compute aITV for each LH
    aITV <-  SumSq %>% 
      summarize(aITV = log(SSintra/SSfixed)) %>% 
      pull(aITV)
    AITV <- c(AITV,aITV)
    TRAIT <- c(TRAIT,ftrait)
    LH <- c(LH,fLH)
    SUMSQ <- rbind(SUMSQ,SumSq) 
  }
}

# aITV ####
data_aITV <- data.frame(aITV = AITV, trait = TRAIT,LifeHistory = LH) %>% 
  spread(key = LifeHistory,value=aITV) %>% 
  arrange(factor(trait),levels = traits) %>% 
  filter(!(trait == "SeedMass")) 
  # filter(!(trait %in% c("Hrepro","SeedMass","Ldelta13C")))
# If aITV inferior to zero: greater contribution of species turnover to total among-community variance


boxplot_aITV <- data_aITV %>% 
  rename(Annuals = annual, Perennials = perennial) %>% 
  gather(key = LifeHistory, value = aITV, - trait) %>% 
  ggplot(aes(x = LifeHistory,y = aITV)) +
  geom_boxplot() +
  theme_classic() +
  geom_hline(yintercept = 0,linetype = "dashed") +
  geom_signif(comparisons = list(c("Annuals", "Perennials")), 
              map_signif_level=TRUE) +
  xlab("")

# stats sur les boxplot:
# - aITV différent de zéro ?
# - différent entre annuelles et pérennes ?
mod_aITV <- lm(aITV ~ LifeHistory, data = data_aITV %>% 
                 gather(key = LifeHistory, value = aITV, - trait))
anova(mod_aITV) # METTRE LA SORTIE D'ANOVA EN LEGENDE ?
summary(mod_aITV)

plot_aITV <- data_aITV %>% 
  # filter(!(trait %in% c("L_Area"))) %>%
  ggplot(aes(x=perennial,y=annual,label = trait))+
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  geom_hline(yintercept = 0,linetype = "dashed")+
  geom_vline(xintercept = 0,linetype = "dashed")+
  xlim(c(-9,2)) +
  ylim(c(-9,2)) +
  ggrepel::geom_label_repel() +
  xlab("aITV of perennials") +
  ylab("aITV of annuals") +
  theme_classic() 

# plots_aITV <- gridExtra::grid.arrange(boxplot_aITV,plot_aITV, ncol=2)
plots_aITV <- ggpubr::ggarrange(boxplot_aITV,plot_aITV,labels = c("A","B"),ncol = 2)

ggsave("draft/plot_aITV.jpg",plots_aITV,width = 8, height = 5)

# Decomposition variance ####
ftrait <- "L_Area"
SUMSQ %>% 
  mutate(sum = SSfixed + SSintra + SScov) %>% 
  mutate(SSfixed = SSfixed / SStot,
         SSintra = SSintra/SStot,
         SScov = SScov/SStot) %>% 
  select(-c(SStot,sum)) %>% 
  gather(key = level,value = SS, -c(LifeHistory,trait)) %>%
  filter(trait == ftrait) %>%
  ggplot(aes(x=level,y=SS,fill = LifeHistory))+
  geom_bar(stat = 'identity',position = "dodge")
